language: php

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: TYPO3_VERSION=^6.2
    - php: 5.4
      env: TYPO3_VERSION=^6.2
    - php: 5.5
      env: TYPO3_VERSION=^6.2
    - php: 5.6
      env: TYPO3_VERSION=^6.2
    - php: 5.5
      env: TYPO3_VERSION=^7.6
    - php: 5.6
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^7.6
    - php: 7.1
      env: TYPO3_VERSION=^7.6
    - php: 7.2
      env: TYPO3_VERSION=^7.6
    - php: 7.0
      env: TYPO3_VERSION=^8
    - php: 7.1
      env: TYPO3_VERSION=^8
    - php: 7.2
      env: TYPO3_VERSION=^8

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - "$HOME/.composer/cache"

notifications:
  slack:
    on_success: change
    on_failure: always
    rooms:
      - secure: "vswi5Un8JoT6mjxu0HFPh9HLo8cLB1qAZHRvsP81k240+Tvpc5Y0mQyvDcQoM1dqGxZaHbZElgdIT3iKL2tecNsOgIFH6k5LhSoebFHirIqtdqD6Ci4VHv35aTuawjky/NrYDfx7jjENYkNpVCyNEqzzM4HcaBQ4Qna9moJRpeJnOi0vJx7YSa397YHIqWb9IRgnBzTVHIjQg3HHMx2EIvVDyRfjkZRgyNIGE1OCuiDevnxT3V2AUSToAGQ1Zr/qHiCIC8CXDJM9o8J6+w9clY2JHS3sdq0nnwlKAfQF830dGA/BkN9vQDo/mZKuJlTXhwxG9rmf3uJBLHm8IfJhmxPogvghEMRhIrDWPgcEIzywE8uII9pbyCLmMlCoC+OnvaKA24nEm81eua1SLIUO17trlH5KUgBcmY/9CI/CQNbTFKVcZoQCMKZrUKQiZHdKK94QNC2DqtlgZeNpgDsmm3coR+q3O2piQBmuBdrITFcssOG0RdLG8glj3eGwpgNm/NRwszM9tYDlg6CjesGqyqNCg/NGjTWQCO2fUj+RtbwkCrBauwjCrFwqAMF0H2BIX1pGvyP3b4IkoFxPe4rigDBRwVJfuxUz6KO57w+icZAnA8wg8SYj0me2wfP6hZ1PnTvAugr24akgo2Zwk6AE//EFwcbwNMPIhb88CSbwFNM="

before_install:
  - composer self-update

before_script:
  - phpenv config-rm xdebug.ini
  - echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - while true; do echo "..."; sleep 60; done &
  - composer require typo3/cms=$TYPO3_VERSION
  - kill %1
  - git checkout composer.json
  - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
  - echo; echo "Running unit tests"; .Build/bin/phpunit --colors -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/
  - echo; echo "Running php lint"; find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - echo; echo "Running PHP Coding Standards Fixer checks"; .Build/bin/php-cs-fixer fix Classes --config=Build/.php_cs.php --dry-run --using-cache=no -v --diff
